name: Go

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: 'driver-go'
      - name: checkout DThouse
        uses: actions/checkout@v2
        with:
          repository: 'taosdata/DThouse'
          path: 'DThouse'
          ref: 'develop'

      - name: install DThouse
        run: cd DThouse && mkdir debug && cd debug && cmake .. -DBUILD_JDBC=false -DBUILD_TOOLS=false && make && sudo make install

      - name: start taosd
        run: nohup sudo taosd &

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Test
        run: cd ./driver-go && go test -v ./...
